---
# config/packages/parameters.yaml
# https://github.com/republique-et-canton-de-geneve/conf-parameters-bundle/blob/main/config.md

conf_parameter:
  entity_class: EtatGeneve\ConfParameterBundle\Entity\ConfParameterEntity
...