name: php-symfony-base

services:
  php84:
    command:
      - /bin/bash
      - -c
      - | 
          mkdir -p /var/www/log/php
          mkdir -p /var/www/log/apache
          chmod a+rx /var/www/Docker/config/php/copy-certificats.sh
          apache2-foreground -c "DocumentRoot /var/www" -c "SetEnv DOCKER_ENVIRONMENT 1"
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.php84
    volumes:
      - ../.:/var/www
      - ./config/php/docker-php.ini:/usr/local/etc/php/conf.d/docker-php.ini
    ports:
      - 80:80
    networks:
      - dev
    extra_hosts:
      - "host.docker.internal:host-gateway"

  saml2:
    command:
      - /bin/bash
      - -c
      - | 
          mkdir -p /var/www/log/php
          mkdir -p /var/www/log/apache
          apache2-foreground -c "DocumentRoot /var/www" -c "SetEnv DOCKER_ENVIRONMENT 1"
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.saml2
    ports:
      - "1050:80"
    volumes:
      - ./config/saml2/config.php:/var/www/simplesamlphp/config/config.php
      - ./config/saml2/acl.php:/var/www/simplesamlphp/config/acl.php
      - ./config/saml2/authsources.php:/var/www/simplesamlphp/config/authsources.php
      - ./config/saml2/saml20-sp-remote.php:/var/www/simplesamlphp/metadata/saml20-sp-remote.php
    networks:
      - dev


  adminer:
    container_name: php-symfony-base-adminer
    build:
      context: .
      dockerfile: Dockerfile.adminer
    restart: always
    volumes:
      - ../data:/var/www/data
      - ../certificates/:/var/www/certs
    ports:
      - 1078:8080
    networks:
      - dev
    extra_hosts:
      - "host.docker.internal:host-gateway"



  # mysql:
  #   image: mysql
  #   restart: always
  #   volumes:
  #     - mysql:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
  #     MYSQL_DATABASE: ${DB_DATABASE}
  #     MYSQL_USER: ${DB_USER}
  #     MYSQL_PASSWORD: ${DB_PASSWORD}
  #   ports:
  #     - 3306:3306
  #   networks:
  #     - dev

  postgres:
    image: php-symfony-base-postgres
    container_name: php-symfony-base-postgres
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_DATABASE
      POSTGRES_USER: $DB_USER
      POSTGRES_DB_EXTENSIONS: pg_trgm
    networks:
      - dev
    volumes:
      - postgres:/var/lib/postgresql
      - ../certificates/postgres:/var/lib/postgresql/certificates
    ports:
      - 5432:5432

  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - dev

  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - 1025:25
      - 8025:8025
    networks:
      - dev

networks:
    dev:
volumes:
    mysql:
    postgres:
    mariadb:
